name: docker_template

services:
  gitlab-ce:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-ce
    restart: always
    ports:
      - 8080:80
      - 443:443
      - 22:22
    volumes:
      - gitlab-ce-config:/etc/gitlab
      - gitlab-ce-data:/var/opt/gitlab
      - gitlab-ce-logs:/var/log/gitlab
    environment:
      TZ: Asia/Jakarta
      # GITLAB_OMNIBUS_CONFIG: external_url="http://gitlab.example.com"; gitlab_rails['smtp_enable'] = true; gitlab_rails['smtp_address'] = "smtp.example.com"; gitlab_rails['smtp_port'] = 587; gitlab_rails['smtp_user_name'] = "user@example.com"; gitlab_rails['smtp_password'] = "password"

volumes:
  gitlab-ce-config:
    driver: local

  gitlab-ce-data:
    driver: local

  gitlab-ce-logs:
    driver: local
