name: docker_template

services:
  oracle-database:
    image: container-registry.oracle.com/database/standard
    container_name: oracle-database
    restart: always
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - oracle-database-orcl:/ORCL
      - oracle-database-data:/opt/oracle/oradata
      - oracle-database-config:/opt/oracle/config
    environment:
      TZ: Asia/Jakarta
      ORACLE_SID: ORCL
      ORACLE_PDB: ORCLPDB
      ORACLE_PWD: password
      ORACLE_CHARACTERSET: AL32UTF8

volumes:
  oracle-database-orcl:
    driver: local

  oracle-database-data:
    driver: local

  oracle-database-config:
    driver: local
