services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - 3000:8080
    volumes:
      - open-webui:/app/backend/data
    environment:
      TZ: Asia/Jakarta

volumes:
  open-webui:
    driver: local
