name: docker_template

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TZ: Asia/Jakarta
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

volumes:
  mariadb:
    driver: local
