name: docker_template

services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    container_name: ollama-nvidia
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    environment:
      TZ: Asia/Jakarta

volumes:
  ollama:
    driver: local
