name: docker_template

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-cpu
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    environment:
      TZ: Asia/Jakarta

volumes:
  ollama:
    driver: local
