services:
  minio-snmd:
    image: quay.io/minio/minio:latest
    container_name: minio-snmd
    command: server data-{1...3} --console-address ":9001"
    restart: always
    environment:
      TZ: Asia/Jakarta
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: minio-snmd
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data-1:/data-1
      - minio:/data-2:/data-2
      - minio:/data-3:/data-3

volumes:
  minio:
    external: true
