name: docker_template

x-minio: &minio-mnmd
  image: quay.io/minio/minio:latest
  command: server http://minio-mnmd-{1...3}/data-{1...3} --console-address ":9001"
  restart: always
  environment:
    TZ: Asia/Jakarta
    MINIO_ROOT_USER: root
    MINIO_ROOT_PASSWORD: minio-mnmd

services:
  minio-mnmd-1:
    <<: *minio-mnmd
    container_name: minio-mnmd-1
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-1-data:/data
      - minio-1-data-1:/data-1
      - minio-1-data-2:/data-2
      - minio-1-data-3:/data-3

  minio-mnmd-2:
    <<: *minio-mnmd
    container_name: minio-mnmd-2
    volumes:
      - minio-2-data:/data
      - minio-2-data-1:/data-1
      - minio-2-data-2:/data-2
      - minio-2-data-3:/data-3

  minio-mnmd-3:
    <<: *minio-mnmd
    container_name: minio-mnmd-3
    volumes:
      - minio-3-data:/data
      - minio-3-data-1:/data-1
      - minio-3-data-2:/data-2
      - minio-3-data-3:/data-3

volumes:
  minio-1-data:
    driver: local

  minio-1-data-1:
    driver: local

  minio-1-data-2:
    driver: local

  minio-1-data-3:
    driver: local

  minio-2-data:
    driver: local

  minio-2-data-1:
    driver: local

  minio-2-data-2:
    driver: local

  minio-2-data-3:
    driver: local

  minio-3-data:
    driver: local

  minio-3-data-1:
    driver: local

  minio-3-data-2:
    driver: local

  minio-3-data-3:
    driver: local
