x-minio: &minio-mnmd
  image: quay.io/minio/minio:latest
  command: server http://minio-mnmd-{1...3}/data-{1...3} --console-address ":9001"
  restart: always
  environment:
    MINIO_ROOT_USER: root
    MINIO_ROOT_PASSWORD: 120500edbMinio

services:
  minio-mnmd-1:
    <<: *minio-mnmd
    container_name: minio-mnmd-1
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - D:\Minio\minio-1\data-1:/data-1
      - D:\Minio\minio-1\data-2:/data-2
      - D:\Minio\minio-1\data-3:/data-3

  minio-mnmd-2:
    <<: *minio-mnmd
    container_name: minio-mnmd-2
    volumes:
      - D:\Minio\minio-2\data-1:/data-1
      - D:\Minio\minio-2\data-2:/data-2
      - D:\Minio\minio-2\data-3:/data-3

  minio-mnmd-3:
    <<: *minio-mnmd
    container_name: minio-mnmd-3
    volumes:
      - D:\Minio\minio-3\data-1:/data-1
      - D:\Minio\minio-3\data-2:/data-2
      - D:\Minio\minio-3\data-3:/data-3

  