services:
  minio-snsd:
    image: quay.io/minio/minio:latest
    container_name: minio-snsd
    command: server data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 120500edbMinio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - D:\Minio\data:/data